apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 32e282c0-092c-43fb-bcc7-1e84dac52e47
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-document-issuer
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/document_issuer
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/document_issuer
