include:
- ./func/*
kind: ArchiveUploadSpec
name: func-TLds

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-document-issuer-66f9aafc-81e8-436b-a380-42e8615c2ebd
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-document-issuer
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-TLds
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-12T17:30:36Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-document-issuer
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-document-issuer
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-document-issuer-66f9aafc-81e8-436b-a380-42e8615c2ebd
      namespace: default
  requestsPerPod: 10000
  resources: {}
